/*
 * StateInnerPanel.java
 *
 * Created on 2010-dec-25, 16:56:08
 */

package com.albatross.visualivr.editor.ui;

import com.albatross.visualivr.editor.ScxmlDataObject;
import javax.swing.JComponent;
import org.apache.commons.scxml.model.Datamodel;
import org.apache.commons.scxml.model.TransitionTarget;
import org.netbeans.modules.xml.multiview.ui.SectionInnerPanel;
import org.netbeans.modules.xml.multiview.ui.SectionView;

/**
 *
 * @author joe
 */
public class TransitionTargetInnerPanel extends SectionInnerPanel  {
    
    private final SectionView view;
    private final TransitionTarget target;
    private final ScxmlDataObject sdo;

    /** Creates new form StateInnerPanel */
    public TransitionTargetInnerPanel(SectionView view, TransitionTarget target, ScxmlDataObject sdo) {
        super(view);
        this.view = view;
        this.target = target;
        this.sdo = sdo;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        idLabel.setText(org.openide.util.NbBundle.getMessage(TransitionTargetInnerPanel.class, "TransitionTargetInnerPanel.idLabel.text")); // NOI18N

        jTextField1.setText(org.openide.util.NbBundle.getMessage(TransitionTargetInnerPanel.class, "TransitionTargetInnerPanel.jTextField1.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(TransitionTargetInnerPanel.class, "TransitionTargetInnerPanel.jLabel1.text")); // NOI18N

        jTextField2.setText(org.openide.util.NbBundle.getMessage(TransitionTargetInnerPanel.class, "TransitionTargetInnerPanel.jTextField2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setValue(JComponent jc, Object o) {

    }

    @Override
    public void linkButtonPressed(Object o, String string) {

    }

    @Override
    public JComponent getErrorComponent(String string) {
       return null;    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
