package com.albatross.visualivr.editor.ui;

import com.albatross.visualivr.editor.ScxmlDataObject;
import com.albatross.visualivr.editor.model.DataTableModel;
import com.albatross.visualivr.palette.items.ui.DataCustomizerPanel;
import com.albatross.visualivr.palette.items.ui.DialogCustomizer;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import org.apache.commons.scxml.model.Data;
import org.apache.commons.scxml.model.Datamodel;
import org.apache.commons.scxml.model.SCXML;
import org.apache.commons.scxml.model.TransitionTarget;
import org.netbeans.modules.xml.multiview.ui.SectionInnerPanel;
import org.netbeans.modules.xml.multiview.ui.SectionView;

/**
 *
 * @author joe
 */
public class ScxmlInnerPanel extends SectionInnerPanel implements TableModelListener {

    private Datamodel datamodel;
    private final ScxmlDataObject sdo;
    private final DefaultComboBoxModel boxModel;
    private final DataTableModel dataTableModel;

    public ScxmlInnerPanel(SectionView sectionView, SCXML scxml, ScxmlDataObject sdo) {
        super(sectionView);
        this.sdo = sdo;
        boxModel = new DefaultComboBoxModel(scxml.getTargets().values().toArray());
        boxModel.setSelectedItem(scxml.getInitialTarget());

        datamodel = scxml.getDatamodel();

        if (datamodel == null) {
            datamodel = new Datamodel();
            scxml.setDatamodel(datamodel);
        }

        this.dataTableModel = new DataTableModel(datamodel);
        this.dataTableModel.addTableModelListener(this);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intitialStateComboBox = new javax.swing.JComboBox();
        intialStateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        datamodelLabel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        intitialStateComboBox.setModel(boxModel);
        intitialStateComboBox.setRenderer(new TransistionTargetRenderer());

        intialStateLabel.setText(org.openide.util.NbBundle.getMessage(ScxmlInnerPanel.class, "ScxmlInnerPanel.intialStateLabel.text")); // NOI18N

        dataTable.setModel(dataTableModel);
        jScrollPane1.setViewportView(dataTable);

        datamodelLabel.setText(org.openide.util.NbBundle.getMessage(ScxmlInnerPanel.class, "ScxmlInnerPanel.datamodelLabel.text")); // NOI18N

        addButton.setText(org.openide.util.NbBundle.getMessage(ScxmlInnerPanel.class, "ScxmlInnerPanel.addButton.text")); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setText(org.openide.util.NbBundle.getMessage(ScxmlInnerPanel.class, "ScxmlInnerPanel.deleteButton.text")); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        errorLabel.setText(org.openide.util.NbBundle.getMessage(ScxmlInnerPanel.class, "ScxmlInnerPanel.errorLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intialStateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intitialStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(datamodelLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton)
                        .addGap(27, 27, 27)
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intialStateLabel)
                    .addComponent(intitialStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datamodelLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(deleteButton)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Data value = new DialogCustomizer<Data>(new DataCustomizerPanel(), "Add Data").getValue();
        
        if(value != null) {
           dataTableModel.addData(value); 
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        
        int selected = dataTable.getSelectedRow();
        
        if(selected > -1) {
            dataTableModel.removeData(selected);
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    @Override
    public void setValue(JComponent jc, Object o) {
    }

    @Override
    public void linkButtonPressed(Object o, String string) {
    }

    @Override
    public JComponent getErrorComponent(String string) {
        return errorLabel;
    }

    @Override
    public void tableChanged(TableModelEvent e) {
        sdo.modelUpdatedFromUI();
    }

    private class TransistionTargetRenderer extends DefaultListCellRenderer {

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

            super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value != null && value instanceof TransitionTarget) {
                TransitionTarget target = (TransitionTarget) value;
                setText(target.getId());
            }

            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel datamodelLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel intialStateLabel;
    private javax.swing.JComboBox intitialStateComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
