/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IfCustomizerPanel.java
 *
 * Created on 2011-jan-09, 10:14:49
 */
package com.albatross.visualivr.palette.items.ui;

import java.util.ArrayList;
import org.apache.commons.scxml.io.SCXMLSerializer;
import org.apache.commons.scxml.model.Action;
import org.apache.commons.scxml.model.ElseIf;
import org.apache.commons.scxml.model.If;

/**
 *
 * @author joe
 */
public class IfCustomizerPanel extends javax.swing.JPanel {

    public static final int IF_MODE = 0;
    public static final int ELSE_IF_MODE = 1;
    private int mode = -1;
    private ExpressionBuilder expressionBuilder;

    public IfCustomizerPanel(int mode) {
        this.mode = mode;

        if (mode != IF_MODE && mode != ELSE_IF_MODE) {
            throw new IllegalArgumentException("Not a valid mode " + mode);
        }

        this.expressionBuilder = new ExpressionBuilder();
        initComponents();

    }

    public String getXml() {

        StringBuffer sb = new StringBuffer();

        if (mode == IF_MODE) {
            If ifToXml = new If();
            ifToXml.setCond(expressionBuilder.getExpression());
            SCXMLSerializer.serializeIf(sb, ifToXml, "");

        } else {
            ElseIf ei = new ElseIf();
            ei.setCond(expressionBuilder.getExpression());
            ArrayList<Action> actions = new ArrayList<Action>();
            actions.add(ei);
            SCXMLSerializer.serializeActions(sb, actions, "");
        }

        return sb.toString();
    }

    public void reset() {
        expressionBuilder.reset();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftComboBox = expressionBuilder.getLeftSideExp();
        opComboBox = expressionBuilder.getOps();
        rightComboBox = expressionBuilder.getRightSideExp();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opComboBox, 0, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox leftComboBox;
    private javax.swing.JComboBox opComboBox;
    private javax.swing.JComboBox rightComboBox;
    // End of variables declaration//GEN-END:variables
}
