/*
 * DataCustomizerPanel.java
 *
 * Created on 2011-jan-09, 16:12:57
 */
package com.albatross.visualivr.palette.items.ui;

import javax.swing.JPanel;
import org.apache.commons.scxml.model.Data;

/**
 *
 * @author joe
 */
public class DataCustomizerPanel extends javax.swing.JPanel implements Customizer<Data> {

    /** Creates new form DataCustomizerPanel */
    public DataCustomizerPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        srcLabel = new javax.swing.JLabel();
        exprLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        srcTextField = new javax.swing.JTextField();
        exprTextField = new javax.swing.JTextField();

        idLabel.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.idLabel.text")); // NOI18N

        srcLabel.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.srcLabel.text")); // NOI18N

        exprLabel.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.exprLabel.text")); // NOI18N

        idTextField.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.idTextField.text")); // NOI18N

        srcTextField.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.srcTextField.text")); // NOI18N

        exprTextField.setText(org.openide.util.NbBundle.getMessage(DataCustomizerPanel.class, "DataCustomizerPanel.exprTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(srcLabel)
                    .addComponent(exprLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exprTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(srcTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srcLabel)
                    .addComponent(srcTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exprLabel)
                    .addComponent(exprTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exprLabel;
    private javax.swing.JTextField exprTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel srcLabel;
    private javax.swing.JTextField srcTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public Data getValue() {
        Data data = new Data();
        data.setId(idTextField.getText());
        data.setSrc(srcTextField.getText());
        data.setExpr(exprTextField.getText());
        return data;
    }

    @Override
    public JPanel getPanel() {
        return this;
    }
}
