/**
 * TODO decide how expressions should be build.
 * should we allow && and ||. It should not be so complex that only programmers 
 * are able to create expressions. 
 * 
 * 
 * TransitionCustomizerPanel.java
 *
 * Created on 2011-jan-07, 16:46:15
 */

package com.albatross.visualivr.palette.items.ui;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import org.apache.commons.scxml.io.SCXMLSerializer;
import org.apache.commons.scxml.model.Transition;

/**
 *
 * @author joe
 */
public class TransitionCustomizerPanel extends javax.swing.JPanel {
    
    private ComboBoxModel events;
    private ComboBoxModel targets;
    private String apos = "&apos;";
    private ExpressionBuilder exprBuilder;
    

    /** Creates new form TransitionCustomizerPanel */
    public TransitionCustomizerPanel() {
        //TODO fill these suckers with values
        events = new DefaultComboBoxModel();
        targets = new DefaultComboBoxModel();
        exprBuilder = new ExpressionBuilder();
        initComponents();
    }
    
    public String getXml() {
        
        Transition trans = new Transition();
        trans.setEvent((String) events.getSelectedItem());
        trans.setNext((String) targets.getSelectedItem());
        trans.setCond(exprBuilder.getExpression());
                
        if(internalRadioButton.isSelected()) {
           //TODO internal?
        }
       
        StringBuffer buffer = new StringBuffer();        
        SCXMLSerializer.serializeTransition(buffer, trans, "");
        return buffer.toString().replace(apos, "'");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtonGroup = new javax.swing.ButtonGroup();
        eventLabel = new javax.swing.JLabel();
        eventsComboBox = new javax.swing.JComboBox();
        targetLabel = new javax.swing.JLabel();
        targetComboBox = new javax.swing.JComboBox();
        typeLabel = new javax.swing.JLabel();
        internalRadioButton = new javax.swing.JRadioButton();
        externalRadioButton = new javax.swing.JRadioButton();
        rightCondComboBox = exprBuilder.getRightSideExp();
        operatorsComboBox = exprBuilder.getOps();
        leftCondComboBox = exprBuilder.getLeftSideExp();
        condLabel1 = new javax.swing.JLabel();

        eventLabel.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.eventLabel.text")); // NOI18N

        eventsComboBox.setEditable(true);
        eventsComboBox.setModel(events);

        targetLabel.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.targetLabel.text")); // NOI18N

        targetComboBox.setEditable(true);
        targetComboBox.setModel(targets);

        typeLabel.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.typeLabel.text")); // NOI18N

        typeButtonGroup.add(internalRadioButton);
        internalRadioButton.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.internalRadioButton.text")); // NOI18N

        typeButtonGroup.add(externalRadioButton);
        externalRadioButton.setSelected(true);
        externalRadioButton.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.externalRadioButton.text")); // NOI18N

        rightCondComboBox.setEditable(true);

        leftCondComboBox.setEditable(true);

        condLabel1.setText(org.openide.util.NbBundle.getMessage(TransitionCustomizerPanel.class, "TransitionCustomizerPanel.condLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(condLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eventsComboBox, 0, 458, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftCondComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(operatorsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rightCondComboBox, 0, 219, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(targetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(targetComboBox, 0, 458, Short.MAX_VALUE))
                    .addComponent(typeLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(internalRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(externalRadioButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventLabel)
                    .addComponent(eventsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightCondComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operatorsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftCondComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(condLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internalRadioButton)
                    .addComponent(typeLabel)
                    .addComponent(externalRadioButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel condLabel1;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JComboBox eventsComboBox;
    private javax.swing.JRadioButton externalRadioButton;
    private javax.swing.JRadioButton internalRadioButton;
    private javax.swing.JComboBox leftCondComboBox;
    private javax.swing.JComboBox operatorsComboBox;
    private javax.swing.JComboBox rightCondComboBox;
    private javax.swing.JComboBox targetComboBox;
    private javax.swing.JLabel targetLabel;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        exprBuilder.reset();
    }

}
